SSTM/Controllers/CourseReminderController.cs
using SSTM.Business.Interfaces;
using SSTM.Core.Course_Reminder;
using SSTM.Core.CourseTrackers;
using SSTM.Filters;
using SSTM.Helpers.App;
using SSTM.Helpers.AutoMapping;
using SSTM.Helpers.Common;
using SSTM.Models.AWS;
using SSTM.Models.Course;
using SSTM.Models.Course_Reminder;
using SSTM.Models.CourseTrackers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace SSTM.Controllers
{
    [Authorize, SessionExpire, ErrorHandler]
    public class CourseReminderController : BaseController
    {
        #region Class Properties Declarations
        private readonly IExceptionLogService _IExceptionLogService;
        private readonly IActivityLogService _IActivityLogService;
        private readonly IConfigService _IConfigService;
        private readonly IUserService _IUserService;
        private readonly IRoleService _IRoleService;

        private readonly ICourseStatusService _ICourseStatusService;
        private readonly ICourseService _ICourseService;
        private readonly ICourseAssignmentService _ICourseAssignmentService;

        private readonly ICourseDocumentService _ICourseDocumentService;
        private readonly ICourseDocVersionService _ICourseDocVersionService;
        private readonly ICourseDocRemarksService _ICourseDocRemarksService;
        private readonly ICourseSharingService _ICourseSharingService;
        private readonly IMainCourseService _IMainCourseService;
        private readonly ISubCourseService _ISubCourseService;
        private readonly ICourseTrackersService _ICourseTrackersService;
        private readonly ICourseDownloadUserService _ICourseDownloadUserService;
        private readonly ICourseReminderService _ICourseReminderService;
        private readonly ICourseRenewalService _ICourseRenewalService;
        private readonly ICourseReminderLatterUndertakingService _ICourseReminderLatterUndertakingService;
        private readonly ICourseReminderTrackerService _ICourseReminderTrackerService;

        public AppSession CurrentSession
        {
            set { Session["AppSession"] = value; }
            get { return (Session["AppSession"] as AppSession); }
        }
        #endregion
        #region Class Properties Definitions
        public CourseReminderController
            (IExceptionLogService exceptionLogService, IActivityLogService activityLogService, IConfigService configService,
            IUserService userService, IRoleService roleService, ICourseStatusService courseStatusService, ICourseService courseService,
            ICourseAssignmentService courseAssignmentService, ICourseDocumentService courseDocumentService,
            ICourseDocVersionService courseDocVersionService, ICourseDocRemarksService courseDocRemarksService,
            ICourseSharingService courseSharingService, IMainCourseService MainCourseService,
            ISubCourseService SubCourseService, ICourseTrackersService CourseTrackersService,
             ICourseDownloadUserService CourseDownloadUserService, ICourseReminderService ICourseReminderService,
             ICourseRenewalService ICourseRenewalService, ICourseReminderLatterUndertakingService ICourseReminderLatterUndertakingService,
             ICourseReminderTrackerService ICourseReminderTrackerService)
        {
            _IExceptionLogService = exceptionLogService;
            _IActivityLogService = activityLogService;
            _IConfigService = configService;
            _IUserService = userService;
            _IRoleService = roleService;

            _ICourseStatusService = courseStatusService;
            _ICourseService = courseService;
            _ICourseAssignmentService = courseAssignmentService;

            _ICourseDocumentService = courseDocumentService;
            _ICourseDocVersionService = courseDocVersionService;
            _ICourseDocRemarksService = courseDocRemarksService;
            _ICourseSharingService = courseSharingService;
            _IMainCourseService = MainCourseService;
            _ISubCourseService = SubCourseService;
            _ICourseTrackersService = CourseTrackersService;
            _ICourseDownloadUserService = CourseDownloadUserService;
            _ICourseReminderService = ICourseReminderService;

            _ICourseRenewalService = ICourseRenewalService;
            _ICourseReminderLatterUndertakingService = ICourseReminderLatterUndertakingService;
            _ICourseReminderTrackerService = ICourseReminderTrackerService;
        }
        #endregion

        // GET: CourseReminder
        public ActionResult Index(bool? MasterCourse, long? MasterCourseId, string Coursename)
        {
            if (MasterCourse == null)
                MasterCourse = true;
            if (MasterCourseId == null)
                MasterCourseId = 0;

            ViewBag.MasterCourse = MasterCourse.ToString();
            ViewBag.MasterCourseId = MasterCourseId;
            ViewBag.Coursename = Coursename;

            return View(CurrentSession);
        }
        #region New Course List

        [HttpGet]
        public ActionResult GetNewCoursesList(bool MasterCourse, long MasterCourseId)
        {
            try
            {
                var sBuilder = new StringBuilder();
                List<CourseReminder> list = new List<CourseReminder>();
                list = CurrentSession.UserRole == "Developer" || CurrentSession.UserRole == "Aassociate Developer" ?
                            _ICourseReminderService.GetAllRecordwithDeveloper(MasterCourse, MasterCourseId, CurrentSession.UserId).ToList() :
                            _ICourseReminderService.GetAllRecord(MasterCourse, MasterCourseId).ToList();

                foreach (var item in list)
                {
                    string renewdate = "", refdoc = "", action = "",
                        renewalform = "", latter = "", Fixdeveloper = "";

                    var course = _ICourseService.GetRecordNewcourseById(item.Id);
                    var SharedCourseList = _ICourseSharingService.GetListofSharedCourseDocs(course.Id);
                    try
                    {
                        renewdate = item.renew_date.Value.ToString("dd/MM/yyyy");
                    }
                    catch (Exception)
                    {
                        renewdate = "";
                    }

                    string courseNameTrack = "";
                    var courseNameTrack1 = course.Statusid;
                    string sharedcourse = "";
                    if (item.steps == 1)
                    {
                        courseNameTrack = "New Course";
                    }
                    else if (item.steps == 2)
                    {
                        courseNameTrack = "Course Proposal";
                    }
                    else if (item.steps == 3)
                    {
                        courseNameTrack = "AEB meeting";
                    }
                    else if (item.steps == 4)
                    {
                        courseNameTrack = "Latter";
                        if (item.director_latter_signature != null)
                        {
                            if (courseNameTrack1 == 1)
                                courseNameTrack = "Draft (By Developer)";
                            else if (courseNameTrack1 == 2)
                                courseNameTrack = "Submitted (By Developer)";
                            else if (courseNameTrack1 == 3)
                                courseNameTrack = "SME Comments";
                            else if (courseNameTrack1 == 4)
                                courseNameTrack = "Improvement (By Developer)";

                            if (SharedCourseList.Count() != 0)
                                courseNameTrack = "Shared";
                        }
                    }

                    string view = "ViewCourseDoc('" + item.doc_file + "')";
                    string delete = "DeleteNewCourseDoc('" + item.Id + "')";
                    string edit = "OpenAddOrUpdateCourseModal('" + item.Id + "')";
                    string fixcourseId = "FixCourseDeveloperModal('" + item.Id + "')";
                    string renew = "OpenAddOrUpdateReminderCourseModal('" + item.Id + "')";
                    string lattertaiking = "OpenLatterCourseModal('" + item.Id + "')";
                    string NewCourse = "NewCourseShowCourse('" + item.Id + "','" + item.course_name.ToString().Replace(" ", "") + "')";
                    if (!string.IsNullOrEmpty(item.doc_file))
                        refdoc = "<a href='javascript:void(0)' style='color: #ff8707; ' class='longnameellipsis' title ='view document' onclick=" + view + ">" + item.doc_file + "</a>";
                    else
                        refdoc = "-";

                    //if ((item.renew_date.Value - item.reminder_created_date.Value).Days <= 0)


                    string subcourse = "<button type='button' title='Sub Course' class='btn btn-warning btn-sm btnSubCourse'>" +
                                    "New Sub Course </button>";

                    if (CurrentSession.UserRole == "Administration" || CurrentSession.UserRole == "Director")
                    {
                        if (item.steps == 2)
                            Fixdeveloper = "<a href='javascript:void(0)' title='Fixing of course developer ' onclick=" + fixcourseId + ">Confirm</a>";
                    }
                    //if (CurrentSession.UserRole == "Administration" || CurrentSession.UserRole == "Director")
                    //{
                    if (CurrentSession.UserRole == "Administration" || CurrentSession.UserRole == "Director")
                    {
                        latter = "<a href='javascript:void(0)' title='latter document' onclick=" + lattertaiking + ">Signature</a>";
                    }
                    else
                    {

SSTM/Views/CourseDocRemarks/ReviewCourseDocument.cshtml
@model SSTM.Models.CourseDocRemarks.CourseDocRemarksModel

@using GleamTech.AspNet.Mvc
@using GleamTech.DocumentUltimate
@using GleamTech.DocumentUltimate.AspNet
@using GleamTech.DocumentUltimate.AspNet.UI

@{
    ViewBag.Title = "Review & give remarks for course document";
    ViewBag.Url = Request.Url;
    Layout = "~/Views/Shared/_Layout.cshtml";

    var currentSession = (SSTM.Helpers.App.AppSession)Session["AppSession"];

    //var documentViewer = new DocumentViewer
    //{
    //    Width = 800,
    //    Height = 600,
    //    Document = Model.DocName,
    //    DeniedPermissions = DocumentViewerPermissions.All
    //}; //old
}

<link href="~/Theme/plugins/summernote/summernote-bs4.css" rel="stylesheet">
<style>
    /*new*/
    .loading-indicator {
        font-size: 8pt;
        background-image: url(../images/loading/loading.gif);
        background-repeat: no-repeat;
        background-position: top left;
        padding-left: 20px;
        height: 18px;
        text-align: left;
    }

    #loading {
        position: absolute;
        left: 45%;
        top: 40%;
        border: 3px solid #B2D0F7;
        background: white url(/Theme/images/loading.gif) repeat-x;
        padding: 10px;
        font: bold 14px verdana,tahoma,helvetica;
        color: #003366;
        width: 180px;
        text-align: center;
    }

    <style > .alert-dismissible {
        padding-right: 1rem;
    }

    #documentViewer {
        width: 100% !important;
    }
</style>  @*old*@
<style>
    #viewer {
        width: 100% !important;
        height: 800px !important;
    }
</style> @*new*@

<!-- Main content -->
<section class="content" style="padding-top:10px;">
    <div class="row">
        @if (currentSession.UserRole != "Developer" && currentSession.UserRole != "HR" && currentSession.UserRole != "Trainer" &&
                                                currentSession.UserRole != "Print Incharge" && ViewBag.DocType == "Course")
        {
            <div class="col-md-6">
                <div class="alert alert-info alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h5><i class="icon fas fa-info-circle"></i> Note!</h5>
                    To assign the remarks and suggention for this document, you can scroll down at the bottom of the page.
                </div>
            </div>

            <div class="col-md-6">
                <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h5><i class="icon fas fa-exclamation-circle"></i> Note!</h5>
                    If there is no any suggestions then you can directly accept the document and it will send accept document
                    notification to Director and Developer.
                </div>
            </div>
        }
        <div style="text-align:center; padding:0 10px 10px 10px;">
            <a onclick="goBack()" href="#">Back to Courses </a> || <a style="color:blueviolet" href="JavaScript: location.reload(true);">Refresh page</a>
        </div>
        <div class="col-md-12 form-group text-center">
            <div id="loading">
                @*//new*@
                <div class="loading-indicator">
                    Page Loading...
                </div>
            </div>
            @*@this.RenderHead(documentViewer)
                @this.RenderBody(documentViewer)*@ @*old*@

                @if (!String.IsNullOrEmpty(ViewBag.pdffullpath))
            {
                    <iframe id="viewer" class="viewer" src="~/DocViewer/DocumentViewer.aspx?path=@ViewBag.pdffullpath" onload="closeProgressIndicator()" frameborder='0'>

                        <p>Your browser does not support iframes.</p>
                    </iframe>

                }
                else
                {
                    @*<iframe id="viewer" class="viewer" src="~/DocViewer/DocumentViewer.aspx?path=@ViewBag.fullpath" onload="closeProgressIndicator()" frameborder='0'>

                            <p>Your browser does not support iframes.</p>
                        </iframe>*@            @*new*@

                if (!String.IsNullOrEmpty(ViewBag.VideoPath))
                {
                    <div class="video-frame" style="margin-left: 25%;">
                        <video width="700" controls controlsList="nodownload" autoplay="autoplay">
                            <source src="@ViewBag.VideoPath" type="video/@ViewBag.videofomat" />
                            Your browser does not support the video tag or the file format of this video.
                        </video>
                    </div>
                }
                else
                {
                    <iframe id="viewer" onload="closeProgressIndicator()" src="~/DocViewer/DocumentViewer.aspx?path=@ViewBag.fullpath" frameborder='0'>
                        <p>Your browser does not support iframes.</p>
                    </iframe>
                    }

                }
            </div>

            @if (currentSession.UserRole != "HR" && currentSession.UserRole != "Trainer" &&
                                                currentSession.UserRole != "Print Incharge" && ViewBag.DocType == "Course")
            {
                <div class="col-md-12 form-group">
                    @using (Html.BeginForm("SaveCourseDocRemarks", "CourseDocRemarks", FormMethod.Post, new { enctype = "multipart/form-data", id = "frmSaveCourseDocRemarks", autocomplete = "off" }))
                {
                        @*@Html.AntiForgeryToken()*@
                        @Html.HiddenFor(m => m.Id)
                        @Html.HiddenFor(m => m.CourseId)
                        @Html.HiddenFor(m => m.DocId)
                        @Html.HiddenFor(m => m.Remarks)
                        @Html.HiddenFor(m => m.Suggestion)
                        @Html.HiddenFor(m => m.ReferenceFile)
                        @Html.HiddenFor(m => m.isCompleted)

                        <div class="card card-warning">
                            <div class="card-header">
                                <h3 class="card-title">Add or update remarks for <strong>@ViewBag.DocName</strong></h3>
                            </div>

                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-6 form-group NoteRemarks">
                                        <label>Remarks</label>
                                        <div id="summerNoteRemarks"></div>
                                        @Html.ValidationMessageFor(m => m.Remarks, null, new { @class = "alert-danger" })
                                    </div>

                                    <div class="col-md-6 form-group NoteSuggestion">
                                        <label>Suggestions</label>
                                        <div id="summerNoteSuggestion"></div>
                                        @Html.ValidationMessageFor(m => m.Suggestion, null, new { @class = "alert-danger" })
                                    </div>

                                    <div class="col-md-12 form-group">
                                        <label>Reference Doc</label>
                                        <input type="file" id="ReferenceDoc" name="ReferenceDoc" />
                                        <label>@Model.ReferenceFile</label>
                                    </div>
                                </div>
                            </div>

                            <div class="card-footer">
                                <button type="submit" class="btn btn-success">
                                    Submit Remarks&nbsp;&nbsp;<i class="fa fa-tasks"></i>
                                </button>

                                <button class="btn btn-warning" onclick="window.history.back()">Back</button>

                                @if (currentSession.UserRole != "Developer")
                                {
                                    <div class="float-right">
                                        <button type="button" id="btnAcceptCourseDoc" class="btn btn-primary">
                                            No remarks? Accept it!&nbsp;&nbsp;<i class="fa fa-check-square"></i>
                                        </button>

                                        <a class="btn btn-default" href="@Url.Action("Index", "Course")">
                                            Close&nbsp;&nbsp;<i class="fa fa-times"></i>
                                        </a>
                                    </div>
                                }
                            </div>
                        </div>
                    }
                </div>
            }
        </div>
    </section>

    @section scripts{
        @Scripts.Render("~/bundles/jqueryval")

        <script src="~/Theme/plugins/summernote/summernote-bs4.min.js"></script>

        <script>
            var userRole = '@currentSession.UserRole';
            localStorage.setItem("userRole", userRole);
            var saveCourseDocRemarksUrl = '@Url.Action("SaveCourseDocRemarks", "CourseDocRemarks", new { area = "" })';
            var acceptCourseDocsUrl = '@Url.Action("AcceptCourseDocs", "CourseDoc", new { area = "" })';

            var courseIndexUrl = '@Url.Action("index", "Course", new { area=""})';
            var NewcourseIndexUrl = '@Url.Action("index", "CourseReminder", new { area=""})';
            function closeProgressIndicator() { //new
                $("#loading").hide();
            }
        </script>

        <script src="~/Scripts/courseDocRemarks/reviewCourseDocument.js"></script>

    }

SSTM/Views/CourseDocRemarks/ReviewCourseDocument_old.cshtml
@model SSTM.Models.CourseDocRemarks.CourseDocRemarksModel

@using GleamTech.AspNet.Mvc
@using GleamTech.DocumentUltimate
@using GleamTech.DocumentUltimate.AspNet
@using GleamTech.DocumentUltimate.AspNet.UI

@{
    ViewBag.Title = "Review & give remarks for course document";
    ViewBag.Url = Request.Url;
    Layout = "~/Views/Shared/_Layout.cshtml";

    var currentSession = (SSTM.Helpers.App.AppSession)Session["AppSession"];

    var documentViewer = new DocumentViewer
    {
        Width = 800,
        Height = 600,
        Document = Model.DocName,
        DeniedPermissions = DocumentViewerPermissions.All
    };
}

<link href="~/Theme/plugins/summernote/summernote-bs4.css" rel="stylesheet">

<style>
    .alert-dismissible {
        padding-right: 1rem;
    }

    #documentViewer {
        width: 100% !important;
    }
</style>

<!-- Main content -->
<section class="content" style="padding-top:10px;">
    <div class="row">
        @if (currentSession.UserRole != "Developer" && currentSession.UserRole != "HR" && currentSession.UserRole != "Trainer" &&
                                        currentSession.UserRole != "Print Incharge" && ViewBag.DocType == "Course")
        {
            <div class="col-md-6">
                <div class="alert alert-info alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h5><i class="icon fas fa-info-circle"></i> Note!</h5>
                    To assign the remarks and suggention for this document, you can scroll down at the bottom of the page.
                </div>
            </div>

            <div class="col-md-6">
                <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h5><i class="icon fas fa-exclamation-circle"></i> Note!</h5>
                    If there is no any suggestions then you can directly accept the document and it will send accept document
                    notification to Director and Developer.
                </div>
            </div>
        }

        <div class="col-md-12 form-group text-center">
            @this.RenderHead(documentViewer)
            @this.RenderBody(documentViewer)
        </div>

        @if (currentSession.UserRole == "Developer" && currentSession.UserRole != "HR" && currentSession.UserRole != "Trainer" &&
                                            currentSession.UserRole != "Print Incharge" && ViewBag.DocType == "Course")
        {
            <div class="col-md-12 form-group">
                @using (Html.BeginForm("SaveCourseDocRemarks", "CourseDocRemarks", FormMethod.Post, new { enctype = "multipart/form-data", id = "frmSaveCourseDocRemarks", autocomplete = "off" }))
                {
                    @*@Html.AntiForgeryToken()*@
                    @Html.HiddenFor(m => m.Id)
                    @Html.HiddenFor(m => m.CourseId)
                    @Html.HiddenFor(m => m.DocId)
                    @Html.HiddenFor(m => m.Remarks)
                    @Html.HiddenFor(m => m.Suggestion)
                    @Html.HiddenFor(m => m.ReferenceFile)
                    @Html.HiddenFor(m => m.isCompleted)

                    <div class="card card-warning">
                        <div class="card-header">
                            <h3 class="card-title">Add or update remarks for <strong>@ViewBag.DocName</strong></h3>
                        </div>

                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6 form-group">
                                    <label>Remarks</label>
                                    <div id="summerNoteRemarks"></div>
                                    @Html.ValidationMessageFor(m => m.Remarks, null, new { @class = "alert-danger" })
                                </div>

                                <div class="col-md-6 form-group">
                                    <label>Suggestions</label>
                                    <div id="summerNoteSuggestion"></div>
                                    @Html.ValidationMessageFor(m => m.Suggestion, null, new { @class = "alert-danger" })
                                </div>

                                <div class="col-md-12 form-group">
                                    <label>Reference Doc</label>
                                    <input type="file" id="ReferenceDoc" name="ReferenceDoc" />
                                    <label>@Model.ReferenceFile</label>
                                </div>
                            </div>
                        </div>

                        <div class="card-footer">
                            <button type="submit" class="btn btn-success">
                                Save Remarks&nbsp;&nbsp;<i class="fa fa-tasks"></i>
                            </button>

                            <div class="float-right">
                                <button type="button" id="btnAcceptCourseDoc" class="btn btn-primary">
                                    No remarks? Accept it!&nbsp;&nbsp;<i class="fa fa-check-square"></i>
                                </button>

                                <a class="btn btn-default" href="@Url.Action("Index","Course")">
                                    Close&nbsp;&nbsp;<i class="fa fa-times"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                }
            </div>
        }
    </div>
</section>

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")

    <script src="~/Theme/plugins/summernote/summernote-bs4.min.js"></script>

    <script>
        var saveCourseDocRemarksUrl = '@Url.Action("SaveCourseDocRemarks", "CourseDocRemarks", new { area = "" })';
        var acceptCourseDocsUrl = '@Url.Action("AcceptCourseDocs", "CourseDoc", new { area = "" })';

        var courseIndexUrl = '@Url.Action("index", "Course", new { area=""})';
    </script>

    <script src="~/Scripts/courseDocRemarks/reviewCourseDocument.js"></script>
}

SSTM/Views/CourseDocRemarks/_ViewCourseDocRemarks.cshtml
@model IEnumerable<SSTM.Models.CourseDocRemarks.CourseDocRemarksGridModel>

<div class="modal-header">
    <h4 id="h4CourseDocsRemarksModal" class="modal-title">Course Documents</h4>

    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
</div>

<div class="modal-body">
    <div class="row">
        <div class="col-md-12 form-group table-responsive">
            <table id="tblCourseDocRemarks" class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Documents</th>
                        <th class="text-center">Status</th>
                        <th>Remarks</th>
                        <th>Suggestion</th>
                        <th>Reference Doc</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Count() > 0)
                    {
                        foreach (var item in Model)
                        {
                            <tr id="@item.Id" course="@item.CourseId">
                                <td>
                                    <strong>@item.DocName</strong>
                                </td>
                                <td class="text-center">
                                    @if (item.isDeleted)
                                    {
                                        <label class="badge badge-secondary">Skipped</label>
                                    }
                                    else if (item.isReassigned)
                                    {
                                        <label class="badge badge-warning">Reassign</label>
                                    }
                                    else if (item.isApproved)
                                    {
                                        <label class="badge badge-success">Approved</label>
                                    }
                                    else if (item.isCompleted)
                                    {
                                        <label class="badge badge-info">Complete</label>
                                    }
                                    else
                                    {
                                        <label class="badge badge-danger">Incomplete</label>
                                    }
                                </td>
                                <td>
                                    @Html.Raw(item.Remarks)
                                </td>
                                <td>
                                    @Html.Raw(item.Suggestion)
                                </td>
                                <td>
                                    @if (item.ReferenceFile != "N/A")
                                    {
                                        <a href="javascript:void(0);" onclick="ViewCourseDoc(this);">
                                            <strong>@item.ReferenceFile</strong>
                                        </a>
                                    }
                                    else
                                    {
                                        <strong>@item.ReferenceFile</strong>
                                    }
                                </td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="5" class="text-center no-data">No data found.</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="modal-footer justify-content-between">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>

<script>
    var loadCourseDocumentUrl = '@Url.Action("LoadCourseDocument", "CourseDoc")';
    var viewCourseDocumentRemarksUrl = '@Url.Action("ViewCourseDocumentRemarks", "CourseDocRemarks")';
   

    function ViewCourseDoc(this1) {
        var courseId = $(this1).closest('tr').attr('course');
        var docId = $(this1).closest('tr').attr('id');

        Ajaxhelper.post(loadCourseDocumentUrl, { courseId: courseId, docId: docId, docType: 'Reference' }, onSuccessLoadDocument, null, null);

        function onSuccessLoadDocument(data) {
            if (data.result)
                window.location = viewCourseDocumentRemarksUrl + data.fs;
            else
                toastr.error(data.message);
        }
    }
</script>