SSTM/Controllers/TrainerUploadDocumentController.cs
using SSTM.Business.Interfaces;
using SSTM.Core.TrainerUploadDocument;
using SSTM.Filters;
using SSTM.Helpers.App;
using SSTM.Helpers.AutoMapping;
using SSTM.Helpers.Common;
using SSTM.Models.AWS;
using SSTM.Models.TrainerUploadDocumentModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SSTM.Controllers
{
    [Authorize, SessionExpire, ErrorHandler]
    public class TrainerUploadDocumentController : Controller
    {
        #region Class Properties Declarations
        private readonly ITrainerUploadDocumentService _ITrainerUploadDocumentService;
        private readonly IExceptionLogService _IExceptionLogService;
        private readonly IConfigService _IConfigService;
        private readonly IUserService _IUserService;
        public AppSession CurrentSession
        {
            set { Session["AppSession"] = value; }
            get { return (Session["AppSession"] as AppSession); }
        }
        public TrainerUploadDocumentController(ITrainerUploadDocumentService ITrainerUploadDocumentService,
            IExceptionLogService exceptionLogService,
             IConfigService configService, IUserService userService)
        {
            _ITrainerUploadDocumentService = ITrainerUploadDocumentService;
            _IExceptionLogService = exceptionLogService;
            _IConfigService = configService;
            _IUserService = userService;
        }
        #endregion
        // GET: TrainerUploadDocument
        public ActionResult Index(bool? MasterCourse, long? MasterCourseId)
        {
            if (MasterCourse == null)
                MasterCourse = true;
            if (MasterCourseId == null)
                MasterCourseId = 0;

            ViewBag.MasterDoc = MasterCourse.ToString();
            ViewBag.MasterDocId = MasterCourseId;

            var list = _ITrainerUploadDocumentService.GetUploadDocsList(0);
            ViewBag.docstatus = 0;//TrainerUploadDocuments
            return View(list);
        }
        public ActionResult CommonDocument(bool? MasterDoc, long? MasterDocId,string DocumentName)
        {
            if (MasterDoc == null)
                MasterDoc = true;
            if (MasterDocId == null)
                MasterDocId = 0;

            ViewBag.MasterDoc = MasterDoc.ToString();
            ViewBag.MasterDocId = MasterDocId;
            ViewBag.DocumentName = DocumentName;

            var list = _ITrainerUploadDocumentService.GetCommonUploadDocsList(2, MasterDoc, MasterDocId);
            ViewBag.docstatus = 2;//TrainerUploadCommonDoc
            return View(list);
        }
        public ActionResult VideoFiles(bool? MasterDoc, long? MasterDocId, string DocumentName)
        {
            if (MasterDoc == null)
                MasterDoc = true;
            if (MasterDocId == null)
                MasterDocId = 0;

            ViewBag.MasterDoc = MasterDoc.ToString();
            ViewBag.MasterDocId = MasterDocId;
            ViewBag.DocumentName = DocumentName;

            var list = _ITrainerUploadDocumentService.GetCommonUploadDocsList(1, MasterDoc, MasterDocId);
            ViewBag.docstatus = 1;//TrainerUploadvideo
            return View(list);
        }

        public ActionResult ConnfidentialDocument(bool? MasterDoc, long? MasterDocId, string DocumentName)
        {
            if (MasterDoc == null)
                MasterDoc = true;
            if (MasterDocId == null)
                MasterDocId = 0;

            ViewBag.MasterDoc = MasterDoc.ToString();
            ViewBag.MasterDocId = MasterDocId;
            ViewBag.DocumentName = DocumentName;

            var list = _ITrainerUploadDocumentService.GetCommonUploadDocsList(3, MasterDoc, MasterDocId);
            ViewBag.docstatus = 1;//ConfindentialDocument
            return View(list);
        }
        [HttpPost]
        public ActionResult SaveDocument(long Id, string DocFileName, int status,bool MasterDoc, long MasterDocId,string ismainfolder)
        {
            #region one table multle menu document Upload
            int statusdata = 0;
            if (status == 0)
                statusdata = (int)TrainingDocumentStatus.UploadDocs;
            else if (status == 1)
                statusdata = (int)TrainingDocumentStatus.video;
            else if (status == 3)
                statusdata = (int)TrainingDocumentStatus.ConfidentialDoc;
            else
                statusdata = (int)TrainingDocumentStatus.CommonDoc;
            #endregion
            if(statusdata==0)
                ismainfolder = "false";

            JsonResult jsOutput = new JsonResult();

            //status => 0 for Upload Docs,1 Video, 2 for common Docs
            try
            {
                TrainerUploadDocument TrainerDocument = new TrainerUploadDocument();

                if (DocFileName != "" && DocFileName != "undefined")
                {
                    string fileName = null;
                    if (ismainfolder != "true")
                    {
                        if (Request.Files.Count > 0)
                        {
                            //  Get all files from Request object  
                            HttpFileCollectionBase files = Request.Files;

                            for (int i = 0; i < files.Count; i++)
                            {
                                HttpPostedFileBase file = files[i];

                                var fileExtension = Path.GetExtension(file.FileName).ToLower();

                                if (statusdata == 2 || statusdata == 0 || statusdata == 3)
                                {
                                    if (fileExtension == ".pdf" || fileExtension.ToLower() == ".doc" || fileExtension.ToLower() == ".docx" || fileExtension.ToLower() == ".pptx" || fileExtension.ToLower() == ".ppt" ||
                                    fileExtension.ToLower() == ".xlsx" || fileExtension.ToLower() == ".xls")
                                    {
                                        #region Save file on cloud storage
                                        // Checking for Internet Explorer  
                                        if (Request.Browser.Browser.ToUpper() == "IE" || Request.Browser.Browser.ToUpper() == "INTERNETEXPLORER")
                                        {
                                            string[] testfiles = file.FileName.Split(new char[] { '\\' });
                                            fileName = testfiles[testfiles.Length - 1];
                                        }
                                        else
                                            fileName = file.FileName;

                                        Random generator = new Random();
                                        //fileName = generator.Next(0, 1000000).ToString("D10") + Path.GetExtension(fileName);
                                        fileName = DocFileName.Replace(" ", "") + "_" + DateTime.Now.ToString("ddMMyyyy") + "_" + DateTime.Now.Hour.ToString() + DateTime.Now.Minute.ToString() + DateTime.Now.Second.ToString() + Path.GetExtension(fileName);

                                        #region one table multle menu document Upload with folder in s3 bucket

                                        string TrainerDocumentdir = "TrainerDocument";
                                        if (status == 0)
                                            TrainerDocumentdir = "TrainerUploadDocuments";
                                        else if (status == 1)
                                            TrainerDocumentdir = "TrainerUploadvideo";
                                        else if (status == 3)
                                            TrainerDocumentdir = "ConfindentialDocument";
                                        else
                                            TrainerDocumentdir = "TrainerUploadCommonDoc";
                                        #endregion

                                        var configEntity = _IConfigService.GetFirstRecord();
                                        AWSModel awsModel = new AWSModel()
                                        {
                                            AccessKey = UtilityHelper.Decrypt(configEntity.AWSAccessKey),
                                            SecreteKey = UtilityHelper.Decrypt(configEntity.AWSSecretKey),
                                            BucketName = UtilityHelper.Decrypt(configEntity.BucketName),
                                            BucketDirectory = TrainerDocumentdir,
                                            FileName = fileName,
                                            LocalFileStream = file.InputStream
                                        };

                                        AWSHelper.UploadFile(awsModel);
                                        #endregion

                                        #region Save record into Trainer Upload Document table
                                        var DocEntity = _ITrainerUploadDocumentService.GetRecordById(Id);
                                        long TrainerCurrentuser = 0;
                                        if (CurrentSession.UserRole == "Trainer")
                                            TrainerCurrentuser = CurrentSession.UserId;

                                        if (DocEntity == null)
                                        {
                                            DocEntity = new TrainerUploadDocumentModel
                                            {
                                                DocumentName = DocFileName,
                                                DocumentPath = fileName,
                                                Status = statusdata,
                                                TrainerId = TrainerCurrentuser,
                                                MasterDoc = MasterDoc,

SSTM/Views/TrainerUploadDocument/CommonDocument.cshtml
@model IEnumerable<SSTM.Core.TrainerUploadDocument.TrainerUploadDocument>
@{
    ViewBag.Title = "Common Document";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var currentSession = (SSTM.Helpers.App.AppSession)Session["AppSession"];
}


@Styles.Render("~/Theme/datatables")

<section class="content" style="padding-top:10px;">
    <!-- Default box -->
    <div class="card col-md-12">
        <div class="card-header row">
            <div class="col-12 row">
                <div class="col-8">
                    <h3 class="card-title">
                        Upload Common Document
                        @if (ViewBag.MasterDoc == "False")
                        {<span>-</span> @ViewBag.DocumentName}
                    </h3>
                </div>
                <div class="col-4">

                    @if (currentSession.UserRole == "Administration" || currentSession.UserRole == "Director")
                    {
                        <button type="button" onclick="OpenAddCommonDocumentModal(0);" class="btn btn-primary btn-sm float-right">
                            <i class="fa fa-plus-square"></i>&nbsp;Add New
                        </button>
                    }
                    &nbsp;&nbsp;
                    @if (ViewBag.MasterDoc == "False")
                    {
                        <input action="action" class="btn btn-warning btn-sm pull-right"
                               onclick="window.history.go(-1);"
                               type="submit"
                               value="<< Back" style="margin-left: 50%;" />
                    }
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="col-md-12 form-group table-responsive mt-3">
                <table id="tblDocuments" class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th style="width: 25%;">Documents Name</th>
                            <th style="width: 25%;">Files</th>
                            <th style="width: 25%;">Sub Document</th>
                            <th style="width: 10%;text-align:center">Actions</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <label>@item.DocumentName</label>
                                </td>
                                <td>
                                    @if(!string.IsNullOrEmpty(item.DocumentPath))
                                    { 
                                        <a href="javascript:void(0)" title="Common document" onclick="ViewCourseDoc('@item.DocumentPath');">@item.DocumentPath</a>
                                    }
                                </td>
                                <td>
                                    <button type='button' onclick="docsubfolder(@item.Id,'@item.DocumentName')" title='Sub Course' class='btn btn-warning btn-sm btnSubDoc'>
                                        Sub Course
                                    </button>
                                </td>
                                <td>
                                    @*<a href="@Url.Action("DownoadDocFile", "TrainerUploadDocument" , new { filename=item.DocumentPath,status=2})" class="btn btn-info btn-sm Download">
                                            Download
                                        </a>*@
                                    @if (currentSession.UserRole == "Administration" || currentSession.UserRole == "Director")
                                    {
                                        <a href="javascript:void(0)" id="btndelete" class="btn btn-danger btn-sm delete" onclick="deletedoc(@item.Id)">
                                            Delete
                                        </a>
                                    }
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>

            </div>
        </div>
    </div>
</section>

<div class="modal fade" id="CommonDocumentModal" style="display: none" aria-hidden="true" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog" style="max-width:50%;">
        <div class="modal-content">
            <div class="modal-header">
                <h4 id="h4CourseDocsModal" class="modal-title">Upload Common Doc</h4>
                <input type="hidden" id="status" value="2" />
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="text-left">
                        <h6> <span style="color:blue">Note :</span> <span style="color:red"> Upload Document File Extention (doc,ppt or xlxs,PDF files)</span></h6>
                    </div>

                    <div class="col-md-12 form-group" >

                        <div class="col-12">
                            <label> File Name :</label>
                            <input type="text" class="form-control" id="DocFilename" style="width:30%" />
                            <div class="col-md-12 form-group mt-2 ">
                                <label class="checkbox-inline">
                                    <input type="checkbox" value="false" id="ismainfolder" /> Is Main Folder
                                </label>
                            </div>
                        </div>
                        <div class="col-12 mt-3" id="fileupload">
                            <input type="file" id="Docfile" multiple="multiple"/>
                            <br />
                            <progress id="fileProgress" style="display: none"></progress>
                        </div>
                        
                    </div>
                   

                </div>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

                <button type="button" id="btnSubmitDocs" class="btn btn-success">
                    Save
                </button>
            </div>
        </div>
    </div>
</div>

<input type="hidden" value="@ViewBag.MasterDoc" id="MasterDoc" />
<input type="hidden" value="@ViewBag.MasterDocId" id="MasterDocId" />
<script src="~/Scripts/trainerDocument/TrainerDocument.js"></script>



@Scripts.Render("~/Theme/datatablesjs")
<script>
    var saveTrainerDocumentUrl = '@Url.Action("SaveDocument", "TrainerUploadDocument")';
    var DeleteTrainerDocumentUrl = '@Url.Action("DeleteCourseDocument", "TrainerUploadDocument")';

    var loadCourseDocumentUrl = '@Url.Action("LoadCommonDocument", "CourseDoc")';
    var courseDocViewerUrl = '@Url.Action("CourseDocViewer", "CourseDoc")';

    var GotoDocUrl = '@Url.Action("CommonDocument", "TrainerUploadDocument")';

    $(document).ready(function () {
        $("#tblDocuments").DataTable({
            'aoColumnDefs': [{
                'bSortable': false,
                'aTargets': [-1] /* 1st one, start by the right */
            }]
        });

    });

    function ViewCourseDoc(fileName) {

        var courseId = "TrainerUploadCommonDoc";
        var docId = 0;

        Ajaxhelper.post(loadCourseDocumentUrl, { path: "TrainerUploadCommonDoc", filename: fileName }, onSuccessLoadDocument, null, null);

        function onSuccessLoadDocument(data) {
            if (data.result)
                window.location = courseDocViewerUrl + data.fs;
            else
                toastr.error(data.message);
        }
    }
    const checkbox = document.getElementById('ismainfolder')

    checkbox.addEventListener('change', (event) => {
        if (event.currentTarget.checked) {
            $("#ismainfolder").val("true");
            $("#fileupload").hide();
        } else {
           
            $("#fileupload").show();
            $("#ismainfolder").val("false");
        }
    })
</script>

SSTM/Views/TrainerUploadDocument/ConnfidentialDocument.cshtml
@{
    ViewBag.Title = "Confidential Document";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var currentSession = (SSTM.Helpers.App.AppSession)Session["AppSession"];
}

@Styles.Render("~/Theme/datatables")
<style>
    hr{
        color:black;
    }
</style>
<section class="content" style="padding-top:10px;">
    <!-- Default box -->
    <div class="card col-md-12">
        <div class="card-header row">
            <div class="col-12 row">
                <div class="col-8">
                    <h3 class="card-title"><i class="fa fa-file"></i> Confidential Document  
                        @if (ViewBag.MasterDoc == "False")
                        {<span>-</span> @ViewBag.DocumentName}</h3>
                    </h3>
                </div>
                <div class="col-4">
                    @if (currentSession.UserRole == "Director" || currentSession.UserRole == "DirectorStaffs")
                    {
                        <button type="button" onclick="OpenAddCommonDocumentModal(3);" class="btn btn-primary btn-sm float-right">
                            <i class="fa fa-plus-square"></i>&nbsp;Add New
                        </button>
                    }
                    &nbsp;&nbsp;
                    @if (ViewBag.MasterDoc == "False")
                    {
                        <input action="action" class="btn btn-warning btn-sm pull-right"
                               onclick="window.history.go(-1);"
                               type="submit"
                               value="<< Back" style="margin-left: 50%;" />
                    }
                </div>

            </div>
        </div>
           
        <div class="card-body">
            <div class="col-md-12 form-group table-responsive mt-3">
                <table id="tblDocuments" class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th style="width: 25%;">Documents Name</th>
                            <th style="width: 25%;">Files</th>
                            <th style="width: 25%;">Sub Document</th>
                            <th style="width: 10%;text-align:center">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (currentSession.UserRole == "Director" || currentSession.UserRole == "DirectorStaffs")
                        {
                            foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        <label>@item.DocumentName</label>
                                    </td>
                                    <td>
                                        <a href="javascript:void(0)" title="Common document" onclick="ViewCourseDoc('@item.DocumentPath');">@item.DocumentPath</a>
                                    </td>
                                    <td>
                                        <button type='button' onclick="docsubfolder(@item.Id,'@item.DocumentName')" title='Sub Course' class='btn btn-warning btn-sm btnSubDoc'>
                                            Sub Course
                                        </button>
                                    </td>
                                    <td>
                                        @*<a href="@Url.Action("DownoadDocFile", "TrainerUploadDocument" , new { filename=item.DocumentPath,status=2})" class="btn btn-info btn-sm Download">
                                            Download
                                        </a>*@
                                        @if (currentSession.UserRole == "Administration" || currentSession.UserRole == "Director" || currentSession.UserRole == "DirectorStaffs")
                                        {
                                            <a href="javascript:void(0)" id="btndelete" class="btn btn-danger btn-sm delete" onclick="deletedoc(@item.Id)">
                                                Delete
                                            </a>
                                        }
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</section>

<div class="modal fade" id="CommonDocumentModal" style="display: none" aria-hidden="true" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog" style="max-width:50%;">
        <div class="modal-content">
            <div class="modal-header">
                <h4 id="h4CourseDocsModal" class="modal-title">Upload Confidential Document</h4>
                <input type="hidden" id="status" value="3" />
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="text-left">
                        <h6> <span style="color:blue">Note :</span> <span style="color:red"> Upload Document File Extention (Doc,ppt or Xlxs,pdf Files)</span></h6>
                    </div>

                    <div class="col-md-12 form-group">
                        <div class="col-12">
                            <label> File Name :</label>
                            <input type="text" class="form-control" id="DocFilename" style="width:30%" />
                            <div class="col-md-12 form-group mt-2 ">
                                <label class="checkbox-inline">
                                    <input type="checkbox" value="false" id="ismainfolder" /> Is Main Folder
                                </label>
                            </div>
                        </div>
                        <div class="col-12 mt-3"  id="fileupload">
                            <input type="file" id="Docfile" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

                <button type="button" id="btnSubmitDocs" class="btn btn-success">
                    Save
                </button>
            </div>
        </div>
    </div>
</div>
<input type="hidden" value="@ViewBag.MasterDoc" id="MasterDoc" />
<input type="hidden" value="@ViewBag.MasterDocId" id="MasterDocId" />
<script src="~/Scripts/trainerDocument/TrainerDocument.js"></script>



@Scripts.Render("~/Theme/datatablesjs")
<script>
    var saveTrainerDocumentUrl = '@Url.Action("SaveDocument", "TrainerUploadDocument")';
    var DeleteTrainerDocumentUrl = '@Url.Action("DeleteCourseDocument", "TrainerUploadDocument")';

    var loadCourseDocumentUrl = '@Url.Action("LoadCommonDocument", "CourseDoc")';
    var courseDocViewerUrl = '@Url.Action("CourseDocViewer", "CourseDoc")';
    var GotoDocUrl = '@Url.Action("ConnfidentialDocument", "TrainerUploadDocument")';

    $(document).ready(function () {
        $("#tblDocuments").DataTable({
            'aoColumnDefs': [{
                'bSortable': false,
                'aTargets': [-1] /* 1st one, start by the right */
            }]
        });
    });

    function ViewCourseDoc(fileName) {

        var courseId = "ConfindentialDocument";
        var docId = 0;

        Ajaxhelper.post(loadCourseDocumentUrl, { path: "ConfindentialDocument", filename: fileName }, onSuccessLoadDocument, null, null);

        function onSuccessLoadDocument(data) {
            if (data.result)
                window.location = courseDocViewerUrl + data.fs;
            else
                toastr.error(data.message);
        }
    }
    const checkbox = document.getElementById('ismainfolder')

    checkbox.addEventListener('change', (event) => {
        if (event.currentTarget.checked) {
            $("#ismainfolder").val("true");
            $("#fileupload").hide();
        } else {

            $("#fileupload").show();
            $("#ismainfolder").val("false");
        }
    })
</script>

SSTM/Views/TrainerUploadDocument/_AddTrainerDocument.cshtml
@model IEnumerable<SSTM.Models.TrainerUploadDocumentModel.TrainerUploadDocumentModel>

<meta http-equiv='cache-control' content='no-cache'>
<meta http-equiv='expires' content='0'>
<meta http-equiv='pragma' content='no-cache'>

@{
    var currentSession = (SSTM.Helpers.App.AppSession)Session["AppSession"];
}
<div class="modal-content">
    <div class="modal-header">
        <h4 id="h4CourseDocsModal" class="modal-title">Upload Documents</h4>

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
    </div>
    <div class="modal-body">
        <div class="row">
            <div class="text-left">
                <h6> <span style="color:blue">Note :</span> <span style="color:red">Please don't upload password based document (doc,ppt or xlxs files) Editor can't support</span></h6>
            </div>

            <div class="col-md-12 form-group">
                <div class="col-12">
                    <label> File Name :</label>
                    <input type="text" class="form-control" id="DocFilename" style="width:30%" />
                </div>
                <div class="col-12 mt-3">
                    <input type="file" id="Docfile"/>
                    <br />
                    <div id='outputImage'></div>
                    <br />
                    @*<progress id="fileProgress" style="display: none"></progress>*@
                    <div class='progress' id="progressDivId">
                        <div class='progress-bar' id='progressBar'></div>
                        <div class='percent' id='percent'>0%</div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="modal-footer justify-content-between">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

        <button type="button" id="btnSubmitDocs" class="btn btn-success">
            Save
        </button>
    </div>
</div>